# Generated by Django 4.2.5 on 2023-10-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=10)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(max_length=100)),
                ('materialprovides', models.CharField(choices=[('debit', 'debitcard'), ('crdt', 'creditcard'), ('cheque', 'chequebook')], max_length=100)),
                ('purpose', models.CharField(choices=[('enqry', 'Enquiry'), ('order', 'Placeorder'), ('return', 'Placereturn')], default='enqry', max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='login',
            name='uname',
            field=models.CharField(max_length=100),
        ),
    ]
