# Generated by Django 4.2.5 on 2023-10-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_detailsmodel_alter_login_password_alter_login_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsmodel',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
