# Generated by Django 4.2.5 on 2023-10-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_remove_detailsmodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsmodel',
            name='address',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
