# Generated by Django 4.2.5 on 2023-10-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_department_remove_detailsmodel_lastname_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='dprtmnt',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Cname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='Dname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='detailsmodel',
            old_name='crs',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='detailsmodel',
            old_name='dprtmnt',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='detailsmodel',
            old_name='firstname',
            new_name='name',
        ),
    ]
